services:
  - type: web
    name: image-crafter
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
